### ISSUE TITLE
Proposal: ensureDefined

### ISSUE THREAD

**Issue by ababkov** [rexlabsio/data-transfer-object#4]
Our DTO's are great because they can be used in a variety of different ways and for a variety of different purposes.

One of the most powerful features is the ability to instantiate a DTO with PARTIAL (i.e. with not all attributes defined), unfortunately this also means that a function can't rely on a DTO that's passed in to have all its properties populated leading to lots of (or no) inline checks to ensure the DTO has been instantiated with certain properties required by that specific function.

## Scenario

Assume the following DTO

```php
/**
* @property-read string $id
* @property-read string $name
* @property-read string $date_of_birth
* @property-read string[] $hobbies
*/
class PersonData extends DataTransferObject{
    public const NAME_UPDATE = 'name_update';

    protected $propertyGroups = [
         self::NAME_UPDATE => ['id', 'name']
    ];
}
```

## ensureDefined

It would be nice to have a complementary function to `isDefined` that throws if expected values haven't been instantiated

```php
function persistName(PersonData $data){
    $data->ensureDefined(['id', 'name']);

    $this->kingOfNamesMicroService->updateName($data->id, $data->name);
}
```

If the PersonData dto was created without the id AND name attributes defined, a useful exception would be thrown. The implmentation of ensureDefined would be something like:

```php
function ensureDefined($propertyNames){
  $missingProperties = array_filter(fn($name) => $this->isDefined($name) === false, $propertyNames);
   if( !empty($missingProperties) ){
     throw new XYZException(sprintf('The following properties must be defined %s and have not been initialized on DTO', implode(', ', $missingProperties));
    }
}
```

## ensureDefinedGroup

It may also be worth exploring defining named sets of properties on the DTO that you could then reference repeatedly in related scenarios.

```php
/**
* @property-read string $id
* @property-read string $name
* @property-read string $date_of_birth
* @property-read string[] $hobbies
*/
class PersonData extends DataTransferObject{
    public const NAME_UPDATE = 'name_update';

    protected $propertyGroups = [
         self::NAME_UPDATE => ['id', 'name']
    ];
}
```

```php
persistName(PersonData $data){
      $data->ensureDefinedGroup(PersonData::NAME_UPDATE); 

     $person = Person::findOrFail($data->id);
     $person->name = $data->name;
     $person->save();
}
```

Not a huge fan of "groups". Other possible names: 

* propertySet
* set
* purpose (e.g. ensureFitForPurpose)
* strictSet
* strictType
* subType
* definedGroup

Type / sub type resonate most strongly i think but needs more though.

**Comment by cerbero90** [comment]
Just my opinion here but I reckon DTOs shouldn't be aware of anything else but transferring data. From this perspective, if we need to ensure that some information is always present, it would make more sense (to me) to create a DTO with only the required data and without the flag `PARTIAL`. Then type-hint the new DTO in methods that require such information.

**Comment by ababkov** [comment]
We're trying to cut down on the number of classes. The dto itself is still the same, all the properties if defined are still valid

**Comment by ababkov** [comment]
Remember also that you can instantiate any dto with any flags including partial even if flag is not defined on the class

**Comment by lachlankrautz** [comment]
Want to call it `assertDefined`. As discussed will just implement the single method and leave the rest to the user.
